# ============================================================================
# 多语言配置
# ============================================================================
# 注意：defaultContentLanguage 与 hasCJKLanguage 必须是顶级配置，不能放在 [languages] 下面

[languages]
[languages.zh-cn]
languageCode = "zh-cn"
languageName = "中文"
title = "积跬步行千里"
weight = 1
