# ****************************************************************************
# 多语言配置
# ****************************************************************************
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true  # CJK 语言优化（摘要/字数统计）

[languages]
[languages.zh-cn]
languageName = "中文"
title = "积跬步行千里"
weight = 1
