# ============================================================================
# Markdown 渲染配置
# ============================================================================

[markup.goldmark.renderer]
unsafe = true  # 允许渲染 HTML

[markup.goldmark.extensions.passthrough]
enable = true  # 允许 HTML 直通

[markup.goldmark.extensions.passthrough.delimiters]
block = [
  ["\\[", "\\]"],
  ["$$", "$$"]
]
inline = [
  ["\\(", "\\)"]
]

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
