# ============================================================================
# 导航菜单
# ============================================================================

# 主菜单（空数组移除所有）
[menu.main]

# 社交菜单
[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jasonchio-cn"
[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/30240401"
[menu.social.params]
icon = "video"

[[menu.social]]
identifier = "email"
name = "Email"
url = "mailto:zyb389120217@gmail.com"
[menu.social.params]
icon = "email"
