# ============================================================================
# 永久链接配置
# ============================================================================
[permalinks]
post = "/p/:slug/"
page = "/:slug/"
